# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: parente@gmail.com
author_name: Peter Parente
has_binder: true
has_settings: true
kind: server
labextension_name: 'jupyterlab-quickopen'
project_short_description: Quickly open a file in JupyterLab by part of its name
python_name: jupyterlab_quickopen
repository: https://github.com/jupyterlab-contrib/jupyterlab-quickopen.git
test: false

